### ISSUE TITLE
Emit warning also if the version is the same

### ISSUE THREAD

**Issue by Jack89ita** [darrenscerri/duplicate-package-checker-webpack-plugin#15]
Hi! First of all thank you for this great plugin, it works very well.
I think it should be extended to emit a warning even if one ore more packages have the same version.
In fact in my project i was including jQuery, with the same version, multiple times but i never noticed the problem untill now.
What do you think about this?
Thank you very much.

**Comment by darrenscerri** [comment]
Hi @Jack89ita. Webpack should dedupe identical files automatically so that shouldn't be a problem, the package won't be included twice in your build. You can confirm this by analysing your bundle with something like https://github.com/webpack-contrib/webpack-bundle-analyzer or https://github.com/danvk/source-map-explorer to confirm. To solve this issue quickly you can run `npm dedupe`.
